name: eco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  scoped_model: ^2.0.0
  image_picker: ^0.8.6
  get: ^4.6.5
  flutter_bloc: ^8.1.1
  flutter_iconly: ^1.0.2
  fluentui_icons: ^1.0.0
  bottom_navy_bar: ^6.0.0
  sliding_up_panel: ^2.0.0+1
  number_inc_dec: ^0.8.0
  http: ^0.13.6
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.11
  luhn: ^1.0.1
  form_field_validator: ^1.1.0
  flutter_spinkit: ^5.1.0
  firebase_auth: ^4.4.0
  firebase_analytics: ^10.1.4
  firebase_core: ^2.13.1
  fluttertoast: ^8.2.1
  firebase_dynamic_links: ^5.0.15
  google_sign_in: ^6.0.2
  provider: ^6.0.5
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.0.15
  shared_preferences: ^2.0.18
  permission_handler: ^10.2.0
  cloud_firestore_platform_interface: ^5.11.5
  dynamic_themes: ^1.1.0
  localization: ^2.1.0
  flutter_localized_locales: ^2.0.4
  firebase_database: ^10.0.16
  country_icons: ^2.0.2
  flutter_share: ^2.0.0
  material_design_icons_flutter: ^6.0.7096
  flutter_local_notifications: ^13.0.0
  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  logging: ^1.1.1
  chewie: ^1.5.0
  flutter_blue: ^0.8.0
  flutter_reactive_ble: ^5.0.3
  flutter_ftms: ^0.6.2
  flutter_blue_plus: ^1.5.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter:


  uses-material-design: true


  assets:
  
      - images/logosemfundopreto.jpeg
      - images/GoogleIcons.png
      - images/iconeKB011.png
      - images/amigos.png
      - images/home.png
      - images/perfil.png
      - images/treinos.png
      - images/config.png
      - images/treinoss.svg
      - images/icons.svg
      - images/esteira.png
      - images/bicicleta.png
      - images/treino3.png
      - images/remo.png
      - icons/flags/png/pt.png
      - icons/flags/png/es.png
      - icons/flags/png/it.png
